# Generated by Django 4.0.6 on 2022-08-05 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_blog_alter_contact_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='StratContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=120)),
                ('file', models.FileField(upload_to='documents/')),
                ('desc', models.TextField()),
                ('price', models.FloatField()),
                ('phone', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Blog',
        ),
    ]
