# Generated by Django 4.0.6 on 2022-08-15 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_employee_phone_alter_stratcontract_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stratcontract',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='documents/'),
        ),
    ]
