# Generated by Django 4.0.6 on 2022-08-15 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_stratcontract_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stratcontract',
            name='file',
            field=models.FileField(blank=True, default=False, null=True, upload_to='documents/'),
        ),
    ]
