# Generated by Django 4.0.6 on 2022-08-15 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_contact_employee_delete_contact1_delete_employee1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='user',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='user',
        ),
        migrations.RemoveField(
            model_name='stratcontract1',
            name='user',
        ),
    ]
