# Generated by Django 4.0.6 on 2022-08-16 14:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_stratcontract1_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Route_From',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route_from', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Route_To',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route_to', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Tourism_Apply_Form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=120)),
                ('phone', models.CharField(max_length=50)),
                ('travel_date', models.CharField(max_length=40)),
                ('persons', models.CharField(max_length=120)),
                ('adult', models.CharField(max_length=100)),
                ('child', models.CharField(max_length=100)),
                ('from_route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.route_from')),
                ('to_route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.route_to')),
            ],
        ),
        migrations.CreateModel(
            name='Tourism',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('expected_rate', models.FloatField()),
                ('route_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.route_from')),
                ('route_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.route_to')),
            ],
        ),
    ]
