# Generated by Django 4.0.6 on 2022-08-16 15:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0015_route_from_route_to_tourism_apply_form_tourism'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourism_apply_form',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
